import type { Application, AutomationRun, CandidateFact, Job, MaterialVersion } from "@/lib/types";

export const candidateFacts: CandidateFact[] = [
  {
    id: "fact-years-4",
    category: "experience",
    label: "Product design experience",
    value: "4+ years",
    evidence: "Product and UX design across consumer health and B2B systems.",
    verified: true,
    source: "Yadi_Guo_UIUX_CV_Hallmark.pdf",
  },
  {
    id: "fact-wocute-growth",
    category: "experience",
    label: "Wocute growth",
    value: "+40% daily active users; +31% retention",
    evidence: "Series of research-led product releases for a women’s health product.",
    verified: true,
    source: "Yadi_Guo_UIUX_CV_Hallmark.pdf",
  },
  {
    id: "fact-wocute-role",
    category: "experience",
    label: "Product Designer · MQJC Technology · Wocute Project",
    value: "2023 to 2025",
    evidence: "Led research and product design for a women's health product, including privacy, Arabic and right-to-left interfaces.",
    verified: true,
    source: "Yadi_Guo_UIUX_CV_Hallmark.pdf",
  },
  {
    id: "fact-tencent-delivery",
    category: "experience",
    label: "Tencent delivery",
    value: "50+ features",
    evidence: "Delivered platform features from definition through launch and iteration.",
    verified: true,
    source: "Yadi_Guo_UIUX_CV_Hallmark.pdf",
  },
  {
    id: "fact-tencent-role",
    category: "experience",
    label: "Interaction Designer · Tencent · WeChat Project",
    value: "2021 to 2023",
    evidence: "Translated merchant, service-team and business needs into flows, reusable patterns and detailed engineering requirements.",
    verified: true,
    source: "Yadi_Guo_UIUX_CV_Hallmark.pdf",
  },
  {
    id: "fact-alipay-research",
    category: "experience",
    label: "Alipay internal platform research",
    value: "Research, workflow redesign, QA and launch support",
    evidence: "Redesigned merchant workflows for an insurance platform.",
    verified: true,
    source: "Yadi_Guo_UIUX_CV_Hallmark.pdf",
  },
  {
    id: "fact-alipay-role",
    category: "experience",
    label: "User Experience Designer Intern · Alipay · Insurance",
    value: "2020",
    evidence: "Interviewed internal users and redesigned merchant workflows; supported QA, launch and later improvements.",
    verified: true,
    source: "Yadi_Guo_UIUX_CV_Hallmark.pdf",
  },
  {
    id: "fact-job-tracker",
    category: "project",
    label: "AI job application tracker",
    value: "Event model, confidence states and human review workflow",
    evidence: "Independent product project built in Vienna in 2026.",
    verified: true,
    source: "Yadi_Guo_UIUX_CV_Hallmark.pdf",
  },
  {
    id: "fact-product-skills",
    category: "skill",
    label: "Product practice",
    value: "Discovery, requirements, workflow mapping, experimentation, stakeholder communication, usability testing",
    evidence: "Skills and background section.",
    verified: true,
    source: "Yadi_Guo_UIUX_CV_Hallmark.pdf",
  },
  {
    id: "fact-technical-skills",
    category: "skill",
    label: "Technical collaboration",
    value: "REST APIs, Django/DRF, HTML/CSS, React, Git/GitHub",
    evidence: "Technical skills section.",
    verified: true,
    source: "Yadi_Guo_UIUX_CV_Hallmark.pdf",
  },
  {
    id: "fact-tools",
    category: "skill",
    label: "Design and research tools",
    value: "Figma, Sketch, Hotjar, Adobe Creative Suite",
    evidence: "Skills sections across the source CVs.",
    verified: true,
    source: "Yadi_Guo_UIUX_CV_Hallmark.pdf; yadi_cv.pdf",
  },
  {
    id: "fact-education-ms",
    category: "education",
    label: "M.S. Human-Computer Interaction",
    value: "Sun Yat-Sen University · 2021",
    evidence: "Education section.",
    verified: true,
    source: "Yadi_Guo_UIUX_CV_Hallmark.pdf",
  },
  {
    id: "fact-education-ba",
    category: "education",
    label: "B.A. Internet and New Media",
    value: "Sun Yat-Sen University · 2019",
    evidence: "Education section.",
    verified: true,
    source: "Yadi_Guo_UIUX_CV_Hallmark.pdf",
  },
  {
    id: "fact-recognition",
    category: "award",
    label: "Recognition",
    value: "Red Dot Design Concept Finalist · 2020; iGEM Gold · Best Software · Best Applied Design Nominee · 2017",
    evidence: "Recognition section.",
    verified: true,
    source: "Yadi_Guo_UIUX_CV_Hallmark.pdf",
  },
  {
    id: "fact-work-authorization",
    category: "experience",
    label: "Austria work authorization",
    value: "Eligible to work in Austria without sponsorship",
    evidence: "Profile statement.",
    verified: true,
    source: "Yadi_Guo_UIUX_CV_Hallmark.pdf",
  },
  {
    id: "fact-languages-fluent",
    category: "language",
    label: "Languages",
    value: "English, Chinese and Cantonese · Fluent",
    evidence: "Languages section.",
    verified: true,
    source: "Yadi_Guo_UIUX_CV_Hallmark.pdf",
  },
  {
    id: "fact-language-german",
    category: "language",
    label: "German",
    value: "Conversational",
    evidence: "Language section; treat as B2 target, not C1/C2 evidence.",
    verified: true,
    source: "Yadi_Guo_UIUX_CV_Hallmark.pdf",
  },
];

export const demoJobs: Job[] = [
  {
    id: "demo-ux-product-designer",
    company: "Demo · Vienna Product Team",
    title: "Product Designer — B2B Workflows",
    track: "design",
    location: "Vienna, Austria",
    remotePolicy: "Hybrid",
    score: 89,
    scoringStatus: "completed",
    listingStatus: "active",
    status: "new",
    languageRequirement: "English; German B2 helpful",
    salaryMin: 52000,
    salaryMax: 65000,
    currency: "EUR",
    tags: ["UX", "B2B", "Design systems", "Research"],
    source: "Demo data",
    sourceUrl: null,
    publishedAt: "2026-08-08T08:00:00.000Z",
    capturedAt: "2026-08-09T05:30:00.000Z",
    summary: "Complex operational workflows, research and reusable interaction patterns.",
    matchReasons: ["Strong B2B workflow evidence", "50+ shipped features", "Research-to-launch ownership"],
    blockers: [],
    jdQuality: "full",
    isDemo: true,
  },
  {
    id: "demo-product-manager",
    company: "Demo · Austrian Health Product",
    title: "Product Manager — Consumer Health",
    track: "product",
    location: "Austria · Remote",
    remotePolicy: "Remote within Austria",
    score: 84,
    scoringStatus: "completed",
    listingStatus: "active",
    status: "shortlisted",
    languageRequirement: "English",
    salaryMin: 48000,
    salaryMax: 62000,
    currency: "EUR",
    tags: ["Product discovery", "Health", "Experimentation", "Analytics"],
    source: "Demo data",
    sourceUrl: null,
    publishedAt: "2026-08-07T08:00:00.000Z",
    capturedAt: "2026-08-09T05:30:00.000Z",
    summary: "Own discovery, prioritisation and experiments for a privacy-sensitive health product.",
    matchReasons: ["Consumer health domain", "Experimentation evidence", "Cross-functional privacy work"],
    blockers: [],
    jdQuality: "full",
    isDemo: true,
  },
  {
    id: "demo-senior-c1",
    company: "Demo · Enterprise Platform",
    title: "Senior UX Lead",
    track: "design",
    location: "Vienna, Austria",
    remotePolicy: "On-site",
    score: 72,
    scoringStatus: "completed",
    listingStatus: "closed",
    listingStatusSource: "demo",
    listingClosedAt: "2026-08-09T05:30:00.000Z",
    status: "archived",
    languageRequirement: "German C1 required",
    salaryMin: 70000,
    salaryMax: null,
    currency: "EUR",
    tags: ["Leadership", "Enterprise UX"],
    source: "Demo data",
    sourceUrl: null,
    publishedAt: "2026-08-06T08:00:00.000Z",
    capturedAt: "2026-08-09T05:30:00.000Z",
    summary: "Lead a German-speaking enterprise design organisation.",
    matchReasons: ["Enterprise workflow adjacency"],
    blockers: ["German C1 required", "Senior requirement exceeds 5 years"],
    jdQuality: "full",
    isDemo: true,
  },
];

export const demoMaterials: MaterialVersion[] = [
  {
    id: "mv-demo-1",
    materialId: "mat-demo-1",
    version: 1,
    jobId: demoJobs[0].id,
    jobTitle: demoJobs[0].title,
    company: demoJobs[0].company,
    kind: "resume_ats",
    language: "en",
    format: "typ",
    status: "draft",
    storagePath: null,
    createdAt: "2026-08-09T06:05:00.000Z",
    model: "deepseek-v4-pro",
    factIds: ["fact-years-4", "fact-tencent-delivery", "fact-product-skills"],
  },
  {
    id: "mv-demo-2",
    materialId: "mat-demo-2",
    version: 1,
    jobId: demoJobs[0].id,
    jobTitle: demoJobs[0].title,
    company: demoJobs[0].company,
    kind: "cover_letter",
    language: "en",
    format: "docx",
    status: "reviewed",
    storagePath: null,
    createdAt: "2026-08-09T06:07:00.000Z",
    model: "deepseek-v4-pro",
    factIds: ["fact-wocute-growth", "fact-tencent-delivery"],
  },
];

export const demoApplications: Application[] = [
  {
    id: "app-demo-1",
    jobId: demoJobs[1].id,
    company: demoJobs[1].company,
    title: demoJobs[1].title,
    status: "applied",
    appliedAt: "2026-08-05T09:30:00.000Z",
    nextAction: "Review interview preparation notes",
    nextActionAt: "2026-08-12T08:00:00.000Z",
    latestMessageAt: "2026-08-08T14:30:00.000Z",
    latestMessageType: "interview",
    stageSource: "demo",
    classificationConfidence: 0.98,
    matchConfidence: 0.97,
    priorityAt: "2026-08-08T14:30:00.000Z",
    requiresReview: false,
    jdQuality: "full",
    updatedAt: "2026-08-08T14:30:00.000Z",
  },
];

export const demoRuns: AutomationRun[] = [
  {
    id: "run-demo-1",
    localDate: "2026-08-09",
    trigger: "scheduled",
    status: "completed",
    discovered: 18,
    deduplicated: 4,
    highScore: 2,
    generated: 2,
    startedAt: "2026-08-09T05:30:02.000Z",
    completedAt: "2026-08-09T05:33:48.000Z",
  },
];
